import { ethers } from "ethers";
import * as dotenv from "dotenv";
import * as fs from "fs";
import * as path from "path";

dotenv.config();

async function main() {
    // Check if environment variables are set
    if (!process.env.SEPOLIA_RPC_URL || !process.env.SEPOLIA_PRIVATE_KEY) {
        throw new Error("Please set your .env variables (SEPOLIA_RPC_URL, SEPOLIA_PRIVATE_KEY)");
    }

    // Initialize provider and wallet
    const provider = new ethers.providers.JsonRpcProvider(process.env.SEPOLIA_RPC_URL);
    const wallet = new ethers.Wallet(process.env.SEPOLIA_PRIVATE_KEY, provider);

    // Define token parameters
    const tokenName = "ExerciseSolutionToken";
    const tokenSymbol = "EXT";

    // Load the ABI and bytecode from the JSON file generated by Hardhat
    const contractPath = path.join(__dirname, "../artifacts/contracts/ExerciseSolutionToken.sol/ExerciseSolutionToken.json");
    const contractJSON = JSON.parse(fs.readFileSync(contractPath, "utf-8"));

    const exerciseSolutionTokenABI = contractJSON.abi;
    const exerciseSolutionTokenBytecode = contractJSON.bytecode;

    // Create a ContractFactory for deployment
    const exerciseSolutionTokenFactory = new ethers.ContractFactory(
        exerciseSolutionTokenABI,
        exerciseSolutionTokenBytecode,
        wallet
    );

    // Deploy the contract
    console.log("Deploying ExerciseSolutionToken...");
    const tokenContract = await exerciseSolutionTokenFactory.deploy(tokenName, tokenSymbol);

    // Wait for deployment to complete
    await tokenContract.deployed();

    console.log(`ExerciseSolutionToken deployed to: ${tokenContract.address}`);
}

main()
    .then(() => process.exit(0))
    .catch((error) => {
        console.error("Error deploying contract:", error);
        process.exit(1);
    });
